### ISSUE TITLE
Question: which secrets need to be created to deploy?

### ISSUE THREAD

**Issue by r0fls** [k8guard/k8guard-start-from-here#32]
I followed the instructions from here https://k8guard.github.io/deploy/minikube/.

However after running `make build-deploy-minikube` and waiting I get:

```
$ kubectl logs k8guard-report-deployment-483960501-23d4t
Error from server (BadRequest): container "k8guard-report" in pod "k8guard-report-deployment-483960501-23d4t" is waiting to start: secrets "k8guard-report-secrets" not found
```

The action and discover pods are running fine.

**Comment by medyagh** [comment]
Hi @r0fls  , report needs password for cassandra,  here is an [example](https://github.com/k8guard/k8guard-start-from-here/blob/master/minikube/report/k8guard-report-secrets.yaml.EXAMPLE)

You can simply rename the `k8guard-report-secrets.yaml.EXAMPLE` to `k8guard-report-secrets.yaml` . does that answer your question ?

The current [developer-setup](https://github.com/k8guard/k8guard-start-from-here/blob/master/Makefile#L20) in the makefile, has been set to do that for you, Did you run `make developer-setup`  ?

**Comment by r0fls** [comment]
Well, that helped get further but cassandra isn't accepting the connection:

```
$ kubectl logs k8guard-report-deployment-483960501-23d4t
time="2017-08-14T21:35:18Z" level=info msg="Connecting to db"
time="2017-08-14T21:35:18Z" level=debug msg="Connecting with usernamecassandra"
panic: gocql: unable to create session: unable to discover protocol version: dial tcp 10.0.0.243:9042: getsockopt: connection refused

goroutine 1 [running]:
main.main()
        /Users/raphael.deem/Documents/code/go/src/github.com/k8guard/k8guard-report/main.go:15 +0xbc
```

**Comment by medyagh** [comment]
hm... I am thinking the cassandra svc is not up yet.  what does `kubectl get svc` say?
can you re-apply all of them from scratch ? and usually wait couple minutes for the cassandra to be up, (based on your CPU/RAM) cassandra container can take time to be up and running and create the db and users.

**Comment by r0fls** [comment]
That did it, thank you

**Comment by medyagh** [comment]
Sweet ! glad that helped . @r0fls we used to have a smaller cassandra image but that one did not support authentication, if you find a better cassandra docker image, please feel free to make a PR. the current cassandra docker image is a bit heavy ! :)
