### ISSUE TITLE
Positive Feedback in Addition to the Shame

### ISSUE THREAD

**Issue by brianberzins** [k8guard/k8guard-start-from-here#34]
- was on the receiving side of an violation
- fixed the problem quickly
- had to wait to see if I didn't get spammed again

I think it would be nice to have a "hey, good job! you fixed the thing!" instead of just silence after a violation has been fixed. You could do something like "you finally fixed it after 712 warnings!" or something.

If not, no worries. But felt like I'd thrown out the idea to make it feel a bit better when people actually take action to fix things.

**Comment by medyagh** [comment]
good idea ! I would also add it to the reports, so show list of all the Fixed violations. and make a metric for it. so you can see over time how many fixes you have.
