### ISSUE TITLE
Are you interested in making a helm chart for deploying this?

### ISSUE THREAD

**Issue by r0fls** [k8guard/k8guard-start-from-here#37]
Would you be interested in putting the kubernetes deployment into a helm chart, or accept a PR that added one?

**Comment by medyagh** [comment]
@r0fls ofcourse we have been talking about it, that would be a great contribution, please do make a PR !

**Comment by medyagh** [comment]
Closed by the referenced PR https://github.com/k8guard/k8guard-start-from-here/pull/38
