### ISSUE TITLE
unable to install k8guardlibs

### ISSUE THREAD

**Issue by avik-so** [k8guard/k8guard-start-from-here#52]
Firstly, thank you very much for this project, it looks great from the outside,
However, I'm having a couple of issues getting it up and running.

First issue, is that `make developer-setup` can't be run again if an error happens during the setup process.

The second issue is that trying to run each command in the make file manually, I keep running into 
`[ERROR]	Unable to export dependencies to vendor directory: mkdir /media/sf_projects/go/src/github.com/k8guard/k8guardlibs/vendor/github.com/docker/distribution/contrib/docker-integration/generated_certs.d/localregistry:5447: protocol error
`
Is there somewhere we can pull the images from instead of building them?

Trying to install via helm also gives the error that it can't find the docker images.

**Comment by medyagh** [comment]
Thanks for creating this issue. the dependency management needs to be updated to the new way. 

The public images are actually available on docker hub.

https://hub.docker.com/u/k8guard
